# -*- coding: utf-8 -*-
"""eigenvalue-eigenvector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pC1yzeDsGcGkg6KcWsDc7WsSPcU9GUtO
"""

import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd

A = np.array([
    [3,1],
    [0,2]
])

# np.linalg.eig → (öz-değerler, öz-vektörler)
# Her SÜTUN bir öz-vektör
oz_degerler, oz_vektorler = np.linalg.eig(A)

print('═══ ÖZ-DEĞER / ÖZ-VEKTÖR ═══')
print(f'Matris A:\n{A}')
print(f'\nÖz-değerler  (λ) : {oz_degerler}')
print(f'\nÖz-vektörler (V) :\n{oz_vektorler}')
print(f'\n1. öz-vektör: {oz_vektorler[:,0]}')
print(f'2. öz-vektör: {oz_vektorler[:,1]}')
# Doğrula: A @ v == λ × v olmalı
v1 = oz_vektorler[:, 0]
l1 = oz_degerler[0]
print(f'\nDoğrulama:')
print(f'A @ v1      = {A @ v1}')
print(f'λ1 × v1    = {l1 * v1}')
print(f'Eşit mi?    {np.allclose(A @ v1, l1 * v1)}')



# Öz-vektörlerin yönünün dönüşümden etkilenmediğini göster
fig = go.Figure()

# Orijinal vektörler (dönüşüm öncesi)
renkler = ['#3498db', '#2ecc71']
etiketler = ['v1 (orijinal)', 'v2 (orijinal)']

for i in range(2):
    v = oz_vektorler[:, i]
    fig.add_annotation(
        x=v[0], y=v[1],
        ax=0, ay=0,
        xref='x', yref='y',
        axref='x', ayref='y',
        arrowhead=3,
        arrowwidth=2,
        arrowcolor=renkler[i]
    )
    fig.add_trace(go.Scatter(
        x=[0, v[0]], y=[0, v[1]],
        mode='lines+text',
        name=etiketler[i],
        line=dict(color=renkler[i], width=2),
        text=['', f'v{i+1}'],
        textposition='top center'
    ))

# Dönüştürülmüş öz-vektörler
etiketler2 = ['A@v1 (sonra)', 'A@v2 (sonra)']
renkler2   = ['#e74c3c', '#e67e22']

for i in range(2):
    v_donusmus = A @ oz_vektorler[:, i]
    fig.add_trace(go.Scatter(
        x=[0, v_donusmus[0]], y=[0, v_donusmus[1]],
        mode='lines+text',
        name=etiketler2[i],
        line=dict(color=renkler2[i], width=2, dash='dash'),
        text=['', f'λ{i+1}·v{i+1}'],
        textposition='top center'
    ))

fig.update_layout(
    title='Öz-vektörler: Dönüşüm Sonrası Sadece Uzar/Kısalır',
    template='seaborn', height=450,
    xaxis=dict(range=[-1, 4], zeroline=True, zerolinewidth=1),
    yaxis=dict(range=[-1, 3], zeroline=True, zerolinewidth=1),
    showlegend=True
)
fig.show()

print('Gözlem: Dönüşüm sonrası öz-vektörlerin YÖNLERİ aynı,')
print('sadece büyüklükleri λ kadar değişti.')

# PCA'nın adımları:
# 1. Veriyi standardize et (ortalama=0, std=1)
# 2. Kovaryans matrisini hesapla
# 3. Kovaryans matrisinin öz-ayrışımını al
# 4. En büyük öz-değerlere karşılık gelen öz-vektörler = ana bileşenler

np.random.seed(42)
n = 200

# Birbiriyle ilişkili iki değişken oluştur
x1 = np.random.normal(0, 2, n)
x2 = 0.8 * x1 + np.random.normal(0, 0.8, n)

X = np.column_stack([x1, x2])

print('═══ KOVARYANS MATRİSİ ═══')
X_std  = (X - X.mean(axis=0)) / X.std(axis=0)
kov    = np.cov(X_std.T)
print(f'Kovaryans matrisi:\n{kov.round(3)}')
print(f'\nKöşegen: varyanslar (her zaman 1, std yaptık)')
print(f'Köşegen dışı: kovaryans = {kov[0,1]:.3f} (güçlü ilişki → büyük)')

# Kovaryans matrisinin öz-ayrışımı
oz_d, oz_v = np.linalg.eig(kov)
sirala     = np.argsort(oz_d)[::-1]
oz_d       = oz_d[sirala]
oz_v       = oz_v[:, sirala]

print(f'\nÖz-değerler (büyükten küçüğe): {oz_d.round(4)}')
print(f'Toplam varyans açıklama:')
for i, d in enumerate(oz_d):
    print(f'  PC{i+1}: %{d/oz_d.sum()*100:.1f}')

# UK Road Safety verisini yükle
accidents = pd.read_csv('./accidents_2016.csv', low_memory=False)

# PCA için sayısal sütunları seç
pca_cols = ['Number_of_Vehicles', 'Number_of_Casualties',
            'Speed_limit', 'Accident_Severity']
df_pca   = accidents[pca_cols].dropna()

# Standardize et — PCA için zorunlu
scaler  = StandardScaler()
X_sc    = scaler.fit_transform(df_pca)

# PCA uygula
pca     = PCA()
X_pca   = pca.fit_transform(X_sc)

print('═══ PCA — UK Road Safety ═══')
print(f'Orijinal boyut   : {X_sc.shape[1]} sütun')
print(f'Örneklem sayısı  : {X_sc.shape[0]:,}')

# Her bileşenin açıkladığı varyans
var_oran = pca.explained_variance_ratio_
print(f'\nBileşen bazında varyans açıklama oranı:')
for i, v in enumerate(var_oran):
    kumulatif = var_oran[:i+1].sum()
    bar       = '█' * int(v * 40)
    print(f'  PC{i+1}: %{v*100:.1f}  (kümülatif: %{kumulatif*100:.1f})  {bar}')

# Kaç bileşen yeterli? → %80 eşiği
n_yeterli = np.argmax(np.cumsum(var_oran) >= 0.80) + 1
print(f'\n%80 varyans için {n_yeterli} bileşen yeterli')
print(f'Boyut azaltma: {X_sc.shape[1]} → {n_yeterli} sütun')

fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=[
        'Explained Variance Ratio',
        'PC1 vs PC2 — Kaza Şiddetine Göre'
    ]
)

# Panel 1: Scree plot
fig.add_trace(go.Bar(
    x=[f'PC{i+1}' for i in range(len(var_oran))],
    y=var_oran * 100,
    marker_color='#3498db',
    name='Varyans %',
    hovertemplate='<b>%{x}</b><br>%{y:.1f}%<extra></extra>',
    showlegend=False
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=[f'PC{i+1}' for i in range(len(var_oran))],
    y=np.cumsum(var_oran) * 100,
    mode='lines+markers',
    name='Kümülatif %',
    line=dict(color='#e74c3c', width=2),
    marker=dict(size=8),
    hovertemplate='<b>%{x}</b><br>Kümülatif: %{y:.1f}%<extra></extra>',
    showlegend=True
), row=1, col=1)

# %80 referans çizgisi
fig.add_hline(y=80, line_dash='dot', line_color='gray',
              annotation_text='%80 eşiği', row=1, col=1)

# Panel 2: PC1 vs PC2 scatter
severity_renk = {1:'#e74c3c', 2:'#e67e22', 3:'#3498db'}
severity_ad   = {1:'Ölümlü', 2:'Ağır Yaralı', 3:'Hafif Yaralı'}

# Örneklem al (136K nokta çok fazla)
idx = np.random.choice(len(X_pca), 2000, replace=False)

for sev in [1, 2, 3]:
    maske = df_pca.iloc[idx]['Accident_Severity'] == sev
    fig.add_trace(go.Scatter(
        x=X_pca[idx][maske.values, 0],
        y=X_pca[idx][maske.values, 1],
        mode='markers',
        name=severity_ad[sev],
        marker=dict(
            color=severity_renk[sev],
            size=4, opacity=0.5
        )
    ), row=1, col=2)

fig.update_layout(
    title='PCA — UK Road Safety 2016',
    template='seaborn', height=450
)
fig.update_xaxes(title_text='Bileşen', row=1, col=1)
fig.update_yaxes(title_text='Varyans (%)', row=1, col=1)
fig.update_xaxes(title_text='PC1', row=1, col=2)
fig.update_yaxes(title_text='PC2', row=1, col=2)

fig.show()

# Loadings: hangi değişken hangi bileşene ne kadar katkı yapıyor?
print('\n═══ PCA LOADINGS ═══')
loadings = pd.DataFrame(
    pca.components_.T,
    columns=[f'PC{i+1}' for i in range(len(var_oran))],
    index=pca_cols
)
print(loadings.round(3))
print('\nYorum: Büyük mutlak değer → o değişken bu bileşeni domine ediyor')

# Accident_Severity'yi çıkar — hedef değişken PCA'ya girmemeli
# Daha fazla sayısal değişken ekle
pca_cols2 = [
    'Number_of_Vehicles',
    'Number_of_Casualties',
    'Speed_limit',
    'Day_of_Week',
    'Light_Conditions',
    'Weather_Conditions',
    'Road_Surface_Conditions',
    'Urban_or_Rural_Area'
]

df_pca2 = accidents[pca_cols2].dropna()
X_sc2   = StandardScaler().fit_transform(df_pca2)

pca2    = PCA()
X_pca2  = pca2.fit_transform(X_sc2)

# Explained variance
var2 = pca2.explained_variance_ratio_
print('═══ GENİŞLETİLMİŞ PCA ═══')
print(f'Orijinal boyut: {X_sc2.shape[1]} sütun')
for i, v in enumerate(var2):
    print(f'PC{i+1}: %{v*100:.1f}  (kümülatif: %{var2[:i+1].sum()*100:.1f})')

n_yeterli2 = np.argmax(np.cumsum(var2) >= 0.80) + 1
print(f'\n%80 için {n_yeterli2} bileşen yeterli')
print(f'Boyut azaltma: {X_sc2.shape[1]} → {n_yeterli2}')

# Loadings
loadings2 = pd.DataFrame(
    pca2.components_.T,
    columns=[f'PC{i+1}' for i in range(len(var2))],
    index=pca_cols2
)
print('\nLoadings (PC1-PC3):')
print(loadings2[['PC1','PC2','PC3']].round(3))