# -*- coding: utf-8 -*-
"""messy-ecommerce-sales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_WceNfDpgbm0I_FKZ_Be1IQLcu2LFTQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from google.colab import drive
warnings.filterwarnings('ignore')

drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Colab Notebooks/messy_ecommerce_sales_data.csv'
df = pd.read_csv(file_path)

print(f'Boyut: {df.shape}')
print('\n--- Sütunlar ve tipler ---')
print(df.dtypes)
print('\n--- İlk 5 satır ---')
df.head()

# 1. Sütun isimlerindeki boşlukları temizle
df.columns = df.columns.str.strip()
print('Sütunlar:', df.columns.tolist())

# 2. Eksik değer haritası
print('\n--- Eksik Değerler ---')
eksik = df.isnull().sum()
eksik_yuzde = (df.isnull().sum() / len(df) * 100).round(2)
eksik_tablo = pd.DataFrame({'Eksik Adet': eksik, 'Yüzde (%)': eksik_yuzde})
print(eksik_tablo[eksik_tablo['Eksik Adet'] > 0])

# 3. Quantity ve Price sütunlarındaki bozuk değerleri tespit et
print('\n--- Quantity benzersiz değerler (sayısal olmayan) ---')
print(df[pd.to_numeric(df['Quantity'], errors='coerce').isnull()]['Quantity'].value_counts())

print('\n--- Price benzersiz değerler (sayısal olmayan) ---')
print(df[pd.to_numeric(df['Price'], errors='coerce').isnull()]['Price'].value_counts())

# 4. Duplicate kontrolü
print(f'\n--- Duplicate satır sayısı: {df.duplicated().sum()} ---')

# 5. Kategorik sütunlardaki tutarsızlıklar
print('\n--- Category değerleri ---')
print(df['Category'].value_counts())

print('\n--- Status değerleri ---')
print(df['Status'].value_counts())

print('\n--- Payment_Method değerleri ---')
print(df['Payment_Method'].value_counts())

# Adim 1: Kopya olustur.
df_clean = df.copy()

# Adim 2: Duplicate verileri sil.
df_clean = df_clean.drop_duplicates()
print(f'Duplicate silindikten sonra boyut: {df_clean.shape}')

# Adim 3: Category tutarsizliklarini duzelt.
df_clean['Category'].str.strip().str.title()
print('\n--- Category duzeltme sonrasi değerler ---')
print(df_clean['Category'].value_counts())

# Adim 4: Price temizleme.
df_clean['Price'] = df_clean['Price'].astype(str).str.replace('$','', regex=False).str.strip()
df_clean['Price'] = pd.to_numeric(df_clean['Price'], errors='coerce')

print(f'\nPrice NaN sayısı (temizlik sonrası): {df_clean["Price"].isnull().sum()}')

# Adim 5: Quantity temizleme.
df_clean['Quantity'] = pd.to_numeric(df_clean['Quantity'], errors='coerce')
print(f'\nQuantity NaN sayısı (temizlik sonrası): {df_clean["Quantity"].isnull().sum()}')

# Adim 6: Eksik degerleri doldur.
## Price => medyan
price_median = df_clean['Price'].median()
df_clean['Price'].fillna(price_median, inplace=True)

## Quantity => medyan
quantity_median = int(df_clean['Quantity'].median())
df_clean['Quantity'].fillna(quantity_median).astype(int)

## Category → mod (en sık görülen kategori) ile doldur
category_mod = df_clean['Category'].mode()[0]
df_clean['Category'] = df_clean['Category'].fillna(category_mod)

print(f'\nPrice medyanı: {price_median:.2f}')
print(f'Quantity medyanı: {quantity_median}')
print(f'Category modu: {category_mod}')

# ADIM 7: Total'i yeniden hesapla ────────────────────────────────────
# Price ve Quantity temizlendi, Total'i baştan hesapla
df_clean['Total'] = df_clean['Price'] * df_clean['Quantity']
print(f'\nTotal NaN sayısı (yeniden hesap sonrası): {df_clean["Total"].isnull().sum()}')

# ADIM 8: Order_Date'i datetime'a çevir ──────────────────────────────
df_clean['Order_Date'] = pd.to_datetime(df_clean['Order_Date'], errors='coerce')
df_clean['Month'] = df_clean['Order_Date'].dt.month
df_clean['Month_Name'] = df_clean['Order_Date'].dt.strftime('%B')
print(f'\nOrder_Date NaN sayısı: {df_clean["Order_Date"].isnull().sum()}')

# ÖZET ────────────────────────────────────────────────────────────────
print('\n══════════════════════════════')
print(f'Temiz veri seti: {len(df_clean)} satır')
print('Kalan eksik değerler:')
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])
print('══════════════════════════════')
df_clean.head()

# ── DÜZELTME 1: Category açık map ile temizle ────────────────────────
kategori_map = {
    'electronics' : 'Electronics',
    'ELECTRONICS'  : 'Electronics',
    'electronic'   : 'Electronics',
    'sports'       : 'Sports',
}
df_clean['Category'] = df_clean['Category'].replace(kategori_map)
print('Category düzeltme sonrası:')
print(df_clean['Category'].value_counts())

# ── DÜZELTME 2: Quantity NaN'larını düzelt ───────────────────────────
qty_medyan = int(df_clean['Quantity'].median())
df_clean['Quantity'] = df_clean['Quantity'].fillna(qty_medyan)
df_clean['Quantity'] = df_clean['Quantity'].astype('Int64')  # nullable integer
print(f'\nQuantity NaN kaldı mı: {df_clean["Quantity"].isnull().sum()}')

# ── DÜZELTME 3: Total'i yeniden hesapla ─────────────────────────────
df_clean['Total'] = df_clean['Price'] * df_clean['Quantity']
print(f'Total NaN kaldı mı: {df_clean["Total"].isnull().sum()}')

# ── DÜZELTME 4: Order_Date NaN'larını raporla ────────────────────────
# 2 satır tarih parse edilemiyor — bu satırları bırakıyoruz (sadece 2 kayıt)
print(f'\nOrder_Date NaN satırlar:')
print(df_clean[df_clean['Order_Date'].isnull()][['ID','Customer_Name','Order_Date']])

# ── FINAL KONTROL ────────────────────────────────────────────────────
print('\n══════════════════════════════')
print('Kalan eksik değerler:')
kalan = df_clean.isnull().sum()
print(kalan[kalan > 0] if kalan.sum() > 0 else '✓ Eksik değer kalmadı!')
print(f'\nFinal veri seti: {len(df_clean)} satır, {len(df_clean.columns)} sütun')
print('══════════════════════════════')

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('E-Commerce Satış Analizi — Temizlenmiş Veri', fontsize=14, fontweight='bold')

# ── 1. Kategoriye göre toplam satış ─────────────────────────────────
cat_sales = df_clean.groupby('Category')['Total'].sum().sort_values(ascending=True)
axes[0,0].barh(cat_sales.index, cat_sales.values, color='steelblue', alpha=0.85)
axes[0,0].set_title('Kategoriye Göre Toplam Satış (₺)')
axes[0,0].set_xlabel('Toplam Satış')
for i, v in enumerate(cat_sales.values):
    axes[0,0].text(v + 100, i, f'{v:,.0f}', va='center', fontsize=9)

# ── 2. Ödeme yöntemine göre sipariş sayısı ──────────────────────────
odeme = df_clean['Payment_Method'].value_counts()
axes[0,1].pie(odeme.values, labels=odeme.index,
              autopct='%1.1f%%', startangle=90,
              colors=['#3498db','#e67e22','#2ecc71','#e74c3c'])
axes[0,1].set_title('Ödeme Yöntemine Göre Sipariş Dağılımı')

# ── 3. Sipariş durumuna göre toplam gelir ───────────────────────────
status_gelir = df_clean.groupby('Status')['Total'].sum().sort_values(ascending=True)
renkler = {'Delivered':'#2ecc71','Shipped':'#3498db',
           'Processing':'#e67e22','Cancelled':'#e74c3c','Returned':'#95a5a6'}
bar_colors = [renkler.get(s, '#bdc3c7') for s in status_gelir.index]
axes[1,0].barh(status_gelir.index, status_gelir.values, color=bar_colors, alpha=0.85)
axes[1,0].set_title('Sipariş Durumuna Göre Toplam Gelir')
axes[1,0].set_xlabel('Toplam Gelir')
for i, v in enumerate(status_gelir.values):
    axes[1,0].text(v + 100, i, f'{v:,.0f}', va='center', fontsize=9)

# ── 4. Aylara göre sipariş sayısı ───────────────────────────────────
aylik = df_clean.dropna(subset=['Month'])
aylik_siparis = aylik.groupby('Month').size()
ay_isimleri = {1:'Oca',2:'Şub',3:'Mar',4:'Nis',5:'May',6:'Haz',
               7:'Tem',8:'Ağu',9:'Eyl',10:'Eki',11:'Kas','Ara':12}
ay_isimleri = {1:'Oca',2:'Şub',3:'Mar',4:'Nis',5:'May',6:'Haz',
               7:'Tem',8:'Ağu',9:'Eyl',10:'Eki',11:'Kas',12:'Ara'}
axes[1,1].bar(aylik_siparis.index, aylik_siparis.values,
              color='mediumpurple', alpha=0.85)
axes[1,1].set_xticks(list(ay_isimleri.keys()))
axes[1,1].set_xticklabels(list(ay_isimleri.values()))
axes[1,1].set_title('Aylara Göre Sipariş Sayısı')
axes[1,1].set_ylabel('Sipariş Sayısı')

plt.tight_layout()
plt.savefig('ecommerce_analiz.png', dpi=150, bbox_inches='tight')
plt.show()

# ── Sayısal özet ────────────────────────────────────────────────────
print('═══ ÖZET İSTATİSTİKLER ═══')
print(f'Toplam Gelir        : {df_clean["Total"].sum():>10,.2f}')
print(f'Ortalama Sipariş    : {df_clean["Total"].mean():>10,.2f}')
print(f'En Çok Satan Ürün   : {df_clean["Product"].value_counts().index[0]}')
print(f'En Yüksek Gelir     : {df_clean["Total"].max():>10,.2f}')
print(f'İptal/İade Oranı    : %{((df_clean["Status"].isin(["Cancelled","Returned"])).sum()/len(df_clean)*100):.1f}')

# Veriyi hazırla
aylik = (
    df_clean.dropna(subset=['Month'])
    .groupby('Month')['Total']
    .sum()
    .reindex(range(1, 13), fill_value=0)
)
ay_isimleri = ['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara']
genel_hedef = aylik.mean()

# Koşullu renk: hedef üstü yeşil, altı kırmızı
renk_listesi = ['#2ecc71' if v > genel_hedef else '#e74c3c' for v in aylik.values]

# GridSpec ile 3 panelli layout
from matplotlib.gridspec import GridSpec
fig = plt.figure(figsize=(16, 10))
gs  = GridSpec(2, 2, figure=fig, hspace=0.4, wspace=0.3)

ax_ust  = fig.add_subplot(gs[0, :])   # üst: tüm genişlik
ax_sol  = fig.add_subplot(gs[1, 0])   # sol alt
ax_sag  = fig.add_subplot(gs[1, 1])   # sağ alt

# ── ÜST: Aylık satış bar + annotasyon + axhline ────────────────────
bars = ax_ust.bar(ay_isimleri, aylik.values, color=renk_listesi,
                  width=0.6, alpha=0.85)

# Çubuk üstü etiketler
for bar in bars:
    h = bar.get_height()
    if h > 0:
        ax_ust.text(
            bar.get_x() + bar.get_width() / 2,
            h + 150,
            f'{h:,.0f}',
            ha='center', va='bottom', fontsize=8, fontweight='bold'
        )

# Ortalama referans çizgisi
ax_ust.axhline(y=genel_hedef, color='black', linestyle='--',
               linewidth=1.5, alpha=0.6,
               label=f'Aylık Ortalama ({genel_hedef:,.0f} TL)')

# Zirve annotasyonu
max_ay_idx = list(aylik.values).index(max(aylik.values))
ax_ust.annotate(
    f'Zirve\n{max(aylik.values):,.0f} TL',
    xy=(max_ay_idx, max(aylik.values)),
    xytext=(max_ay_idx - 2, max(aylik.values) - 2000),
    fontsize=9, fontweight='bold', color='darkgreen',
    arrowprops=dict(arrowstyle='->', color='darkgreen', lw=1.5),
    bbox=dict(boxstyle='round,pad=0.3', facecolor='#eafaf1',
              edgecolor='darkgreen', alpha=0.9)
)

ax_ust.set_title('Aylık Satış Performansı', fontsize=13, fontweight='bold')
ax_ust.set_ylabel('Toplam Satış (TL)')
ax_ust.set_ylim(0, max(aylik.values) * 1.2)
ax_ust.legend(loc='upper left', fontsize=9)
for spine in ['top', 'right']:
    ax_ust.spines[spine].set_visible(False)

# ── SOL ALT: Kategoriye göre satış ────────────────────────────────
cat_sales = df_clean.groupby('Category')['Total'].sum().sort_values()
palet = sns.color_palette("colorblind", n_colors=len(cat_sales))
ax_sol.barh(cat_sales.index, cat_sales.values, color=palet, alpha=0.85)
for i, v in enumerate(cat_sales.values):
    ax_sol.text(v + 200, i, f'{v:,.0f}', va='center', fontsize=9)
ax_sol.set_title('Kategoriye Göre Toplam Satış', fontsize=11, fontweight='bold')
ax_sol.set_xlabel('Toplam Satış (TL)')
ax_sol.set_xlim(0, max(cat_sales.values) * 1.2)
for spine in ['top', 'right']:
    ax_sol.spines[spine].set_visible(False)

# ── SAĞ ALT: Ödeme yöntemi pasta ──────────────────────────────────
odeme = df_clean['Payment_Method'].value_counts()
renkler_pasta = sns.color_palette("colorblind", n_colors=len(odeme))
ax_sag.pie(
    odeme.values,
    labels=odeme.index,
    autopct='%1.1f%%',
    colors=renkler_pasta,
    startangle=90,
    pctdistance=0.75
)
ax_sag.set_title('Ödeme Yöntemi Dağılımı', fontsize=11, fontweight='bold')

# ── ANA BAŞLIK ──────────────────────────────────────────────────────
fig.suptitle('E-Commerce Satış Dashboard — 2024/2025',
             fontsize=16, fontweight='bold', y=1.01)

plt.savefig('ecommerce_dashboard.png', dpi=300,
            bbox_inches='tight', facecolor='white')
plt.show()
print('Dashboard kaydedildi: ecommerce_dashboard.png')
