# -*- coding: utf-8 -*-
"""staj-final-projesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8fNdhjteBE1kMRtuALsaA745QM8P3DI
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from mpl_toolkits.mplot3d import Axes3D

from sklearn.datasets import load_iris, fetch_california_housing
from sklearn.preprocessing import StandardScaler

# Görsel ayarlar
plt.rcParams['figure.figsize'] = (9, 6)
plt.rcParams['font.size'] = 11
np.set_printoptions(precision=3, suppress=True)



print("Kütüphaneler hazır")

"""Not: Iris Setosa, Iris Versicolor ve Iris Virginica, makine öğrenmesi ve istatistikte en bilinen veri setlerinden biri olan Iris (Süsen Çiçeği) Veri Seti'ndeki 3 farklı çiçek türüdür.

Veri setindeki sınıflandırılmak istenen hedef değişkenleri (target / class) bu üç türden oluşur.
"""

iris = load_iris()
X_iris = iris.data # (150, 4)
y_iris = iris.target # tur (1, 2, 3)
iris_feature_names = iris.feature_names
iris_target_names = iris.target_names

housing = fetch_california_housing()
X_house = housing.data      # (20640, 8)
y_house = housing.target    # ev fiyatı (100k $ birimiyle)
house_feature_names = housing.feature_names

print("Iris veri seti:", X_iris.shape, "| Özellikler:", iris_feature_names)
print("Housing veri seti:", X_house.shape, "| Özellikler:", house_feature_names)

# 1 - Veri Noktalari Olarak Vektorler

# Sadece petal length (x) ve petal width (y) -> 2D vektör

X2 = X_iris[:, [2, 3]]

fig, ax = plt.subplots(figsize=(7, 7))
colors = ['#e74c3c', '#3498db', '#2ecc71']

# İlk 5 örneği gerçek vektör (ok) olarak çiz
for i in range(5):
    v = X2[i]
    c = colors[y_iris[i]]
    ax.annotate('', xy=v, xytext=(0, 0),
                arrowprops=dict(arrowstyle='->', color=c, lw=2))
    ax.text(v[0]+0.05, v[1]+0.05, f"v{i}=({v[0]:.1f},{v[1]:.1f})", fontsize=9, color=c)

# Tüm veri setini de zayıf noktalar olarak göster
for cls in range(3):
    mask = y_iris == cls
    ax.scatter(X2[mask, 0], X2[mask, 1], color=colors[cls], alpha=0.25,
               label=iris_target_names[cls])

ax.axhline(0, color='gray', lw=0.8)
ax.axvline(0, color='gray', lw=0.8)
ax.set_xlabel('Petal Length (özellik 1)')
ax.set_ylabel('Petal Width (özellik 2)')
ax.set_title('Her çiçek, orijinden çıkan bir VEKTÖRDÜR')
ax.legend()
ax.set_xlim(-0.5, 7.5)
ax.set_ylim(-0.5, 3)
ax.set_aspect('equal')
plt.tight_layout()
plt.show()

"""Gözlem: İlk 5 çiçeğin her biri, kalın oklarla gösterilen birer vektördür. Arka plandaki soluk noktalar ise tüm veri setinin (150 vektörün) uç noktalarıdır — sınıflar (renkler) uzayda farklı bölgelerde kümelendiği için ayırt edilebilirler. Bu, sınıflandırma problemlerinin geometrik özüdür: vektörleri uzayda ayıran bir sınır bulmak.

Iris Setosa çiçeği yaprak boyutları (özellikle taç yaprak / petal) diğer iki türe göre oldukça küçük olduğu için kolayca ayrıldı.
"""

# 2 - Nokta Çarpımı (Dot Product): Benzerlik Ölçüsü

# İki veri noktası (örn. iki çiçek) ne kadar "benzer yönde" ise o kadar benzerdir. (Kosinus benzerligi)

def cosine_similarity(v, w):
  return np.dot(v, w) / (np.linalg.norm(v) * np.linalg.norm(w))

# Her sınıftan bir örnek alalım (4 boyutlu tam vektör)
sample_idx = [0, 50, 100]  # setosa, versicolor, virginica
samples = X_iris[sample_idx]
labels = [iris_target_names[y_iris[i]] for i in sample_idx]

print("Kosinüs Benzerlik Matrisi (4 boyutlu tam özellik vektörleriyle):\n")
print(f"{'':15}", *[f"{l:12}" for l in labels])
for i, vi in enumerate(samples):
    row = [cosine_similarity(vi, vj) for vj in samples]
    print(f"{labels[i]:15}", *[f"{r:12.3f}" for r in row])

# Görselleştirme: benzerlik matrisini ısı haritası olarak göster
sim_matrix = np.array([[cosine_similarity(vi, vj) for vj in samples] for vi in samples])
fig, ax = plt.subplots(figsize=(5, 4))
im = ax.imshow(sim_matrix, cmap='YlOrRd', vmin=0.9, vmax=1.0)
ax.set_xticks(range(3)); ax.set_xticklabels(labels, rotation=20)
ax.set_yticks(range(3)); ax.set_yticklabels(labels)
for i in range(3):
    for j in range(3):
        ax.text(j, i, f"{sim_matrix[i,j]:.3f}", ha='center', va='center')
ax.set_title('Kosinüs Benzerliği (v · w / |v||w|)')
plt.colorbar(im)
plt.tight_layout()
plt.show()

"""Not: Aynı türün kendisiyle benzerliği tam olarak 1.0'dır (aynı yön). Farklı türler arasında benzerlik 1.0'dan daha düşüktür — bu da nokta çarpımının, ham Öklid mesafesinden farklı olarak, yön benzerliğini yakaladığını gösterir.

Gözlem 1: Versicolor ile Virginica En Benzer Türlerdir ($0.982$):
İki tür arasındaki kosinüs benzerliği $0.982$ gibi mükemmele çok yakın bir değerdir. Bu durum, yaprak boyutlarının birbirine oranının hemen hemen aynı olduğunu ve öznitelik uzayında neredeyse aynı doğrultuda bulunduklarını gösterir. Makine öğrenmesi modellerinin (SVM, Logistic Regression vb.) bu iki türü birbirinden ayırırken en çok zorlanmasının mantıksal sebebi tam olarak bu yüksek benzerliktir.

Gözlem 2: Setosa ile Virginica En Uzak Türlerdir ($0.860$):
Benzerlik puanı $0.860$ ile matristeki en düşük değerdir. Setosa'nın özellikle çok küçük petal (taç yaprak) boyutlarına sahip olması, vektör açısını Virginica'dan belirgin şekilde uzaklaştırır.

Gözlem 3: Setosa ile Versicolor Aradaki Köprüdür ($0.928$):
Setosa, Versicolor'a ($0.928$), Virginica'ya kıyasla ($0.860$) daha yakındır. Boyut sıralamasında Versicolor ortada yer aldığı için bu durum geometrik olarak beklentiyle tam örtüşür.
"""

# 3 - Lineer Dönüşümler: Matrisler Uzayı Nasıl Değiştirir?

# Bir matris, uzaydaki ızgarayı (grid) nasıl deforme ettiğini gösteren bir dönüşümdür. Sütunları, temel vektörlerin (î, ĵ) nereye gittiğini söyler.

# StandardScaler, PCA, hatta bir sinir ağının her katmanı, veriye uygulanan birer lineer dönüşümdür.

def plot_grid_transform(ax, M, title, xlim=(-3,3), ylim=(-3,3)):
    """Bir matrisin 2D ızgarayı nasıl dönüştürdüğünü çizer."""
    grid_range = np.arange(-4, 5, 1)
    for gx in grid_range:
        pts = np.array([[gx, y] for y in np.linspace(-4, 4, 50)])
        tpts = pts @ M.T
        ax.plot(tpts[:,0], tpts[:,1], color='lightgray', lw=0.7, zorder=1)
    for gy in grid_range:
        pts = np.array([[x, gy] for x in np.linspace(-4, 4, 50)])
        tpts = pts @ M.T
        ax.plot(tpts[:,0], tpts[:,1], color='lightgray', lw=0.7, zorder=1)

    # temel vektörler î ve ĵ'nin gittiği yer
    i_hat = M @ np.array([1,0])
    j_hat = M @ np.array([0,1])
    ax.annotate('', xy=i_hat, xytext=(0,0), arrowprops=dict(arrowstyle='->', color='red', lw=2.5))
    ax.annotate('', xy=j_hat, xytext=(0,0), arrowprops=dict(arrowstyle='->', color='blue', lw=2.5))
    ax.text(*i_hat, "  î'", color='red', fontsize=12, fontweight='bold')
    ax.text(*j_hat, "  ĵ'", color='blue', fontsize=12, fontweight='bold')

    ax.set_xlim(xlim); ax.set_ylim(ylim)
    ax.set_aspect('equal')
    ax.set_title(title)
    ax.axhline(0, color='k', lw=0.5); ax.axvline(0, color='k', lw=0.5)

# Örnek dönüşüm: ölçekleme + kesme (shear)
M_scale = np.array([[2, 0],
                     [0, 0.5]])
M_shear = np.array([[1, 0.8],
                     [0, 1]])

fig, axes = plt.subplots(1, 2, figsize=(13, 6))
plot_grid_transform(axes[0], M_scale, "Ölçekleme Matrisi\nM = [[2,0],[0,0.5]]")
plot_grid_transform(axes[1], M_shear, "Kesme (Shear) Matrisi\nM = [[1,0.8],[0,1]]")
plt.tight_layout()
plt.show()

# 4 - Gerçek veri örneği - İris

X2 = X_iris[:, [2, 3]]  # petal length & width
scaler = StandardScaler()
X2_scaled = scaler.fit_transform(X2)

# StandardScaler'ın uyguladığı lineer dönüşüm, köşegen bir matristir:
S = np.diag(1 / scaler.scale_)
print("StandardScaler'ın örtük dönüşüm matrisi (merkezleme sonrası):")
print(S)

fig, axes = plt.subplots(1, 2, figsize=(13, 6))
for cls in range(3):
    mask = y_iris == cls
    axes[0].scatter(X2[mask,0], X2[mask,1], color=colors[cls], label=iris_target_names[cls], alpha=0.7)
    axes[1].scatter(X2_scaled[mask,0], X2_scaled[mask,1], color=colors[cls], label=iris_target_names[cls], alpha=0.7)

axes[0].set_title("Orijinal Uzay (ham özellikler)")
axes[0].set_xlabel('Petal Length'); axes[0].set_ylabel('Petal Width')
axes[1].set_title("Dönüştürülmüş Uzay (StandardScaler)")
axes[1].set_xlabel('Petal Length (z-score)'); axes[1].set_ylabel('Petal Width (z-score)')
for ax in axes:
    ax.legend(); ax.axhline(0,color='gray',lw=0.5); ax.axvline(0,color='gray',lw=0.5)
plt.tight_layout()
plt.show()

"""StandardScaler lineer (doğrusal) bir dönüşümdür. Sağdaki ve soldaki noktaların birbiriyle olan göreceli konumları, yönleri ve açıları birebir aynıdır. Standartlaştırma verinin şeklini, küme içi kümelenmeyi veya sınıf ayrılabilirliğini bozmaz ya da geliştirmez.

Gözlem: Noktaların göreli konumu (kümelenme yapısı) korunuyor, ama eksenler yeniden ölçekleniyor. Uzay deforme oluyor ama orijin sabit kalıyor ve doğrular doğru kalıyor. Bu, "lineer" dönüşümün tanımıdır.

Bu grafik standartlaştırmanın türler arasındaki mesafeyi/oranı değiştirmediğini, sadece tüm öznitelikleri ortak bir ölçekte sıfır noktasına merkeze aldığını açıkça kanıtlıyor.

Neden Standart Scaling yaptık?

Görsel ve Geometrik Kolaylık: Yüklediğin sağdaki grafikte fark ettiğin gibi, $0$ çizgisi tam merkezdedir. Değerin negatif mi pozitif mi olduğuna bakarak verinin ortalamanın altında mı üstünde mi kaldığını tek bakışta anlarsın.

PCA (Temel Bileşenler Analizi) ve Kovaryans Hesapları: PCA gibi boyut indirgeme yöntemleri, verinin eksen etrafındaki varyansını hesaplar. Veri sıfıra merkezlenmediğinde kovaryans matrisi ve özvektör (eigenvector) hesaplamaları yanlış veya kaymış sonuçlar verir.

Kosinüs Benzerliği: Kosinüs benzerliği orijinden çıkan vektörler arasındaki açıya bakar. Eğer veri merkezlenmezse (tüm değerler pozitif kalırsa), tüm vektörler $1.$ bölgede sıkışır ve aralarındaki açı yapay olarak birbirine çok yakın çıkar. Merkezleme yapıldığında gerçek yönsel farklar ortaya çıkar.
"""

# 5 - Matris Çarpımı

# AB çarpımı, "önce B uygula, sonra A uygula" demektir — iki ardışık dönüşümün tek bir dönüşümde birleştirilmesidir.

theta = np.radians(30)
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])  # 30 derece döndürme
S = np.array([[1.5, 0],
              [0, 0.7]])                          # eksenel ölçekleme

combined = R @ S   # önce S (ölçekle), sonra R (döndür)

fig, axes = plt.subplots(1, 3, figsize=(16, 5.5))
plot_grid_transform(axes[0], S, "1) Önce Ölçekle (S)")
plot_grid_transform(axes[1], R, "2) Sonra Döndür (R)")
plot_grid_transform(axes[2], combined, "Birleşik Dönüşüm\n(R @ S)")
plt.tight_layout()
plt.show()

print("S matrisi:\n", S)
print("\nR matrisi:\n", R)
print("\nR @ S (birleşik):\n", combined)

"""**Gözlem:** Son panel, ilk iki dönüşümün **art arda uygulanmasıyla tam olarak aynı sonucu**
veriyor — çünkü `R @ S` matrisi bu bileşimi tek bir matriste kodluyor. `sklearn` pipeline'larındaki
`Pipeline([('scale', StandardScaler()), ('pca', PCA())])` mantığı da matematiksel olarak budur.
"""

# Ters Matris ve Lineer Sistemler: Normal Denklem ile Regresyon

#  Ax = b denklemini çözmek, "hangi vektör x, A dönüşümü altında b'ye gider?" sorusunu sormaktır. Eğer A tersinirse, tek çözüm x = A⁻¹b'dir.

# Veri biliminde lineer regresyonun kapalı-form çözümü olan normal denklem bu fikri kullanır.

# sklearn'ün LinearRegression'ı arka planda bunu yapar. California Housing verisiyle, "medyan gelir" özelliğinden "ev fiyatını" tahmin edelim.

from sklearn.linear_model import LinearRegression

# Basitlik için tek özellik: MedInc (medyan gelir)
x = X_house[:, house_feature_names.index('MedInc')]
y = y_house

# Tasarım matrisi X = [1, x] (bias terimi için 1'ler sütunu ekliyoruz)
X_design = np.column_stack([np.ones_like(x), x])

# --- NORMAL DENKLEM: elle lineer cebirle çözüm ---
beta_manual = np.linalg.inv(X_design.T @ X_design) @ X_design.T @ y
print("Elle (Normal Denklem) hesaplanan katsayılar [bias, eğim]:", beta_manual)

# --- sklearn ile doğrulama ---
model = LinearRegression()
model.fit(x.reshape(-1,1), y)
print("sklearn'ün bulduğu katsayılar   [bias, eğim]:", [model.intercept_, model.coef_[0]])

# Görselleştirme
fig, ax = plt.subplots(figsize=(8,6))
idx = np.random.RandomState(42).choice(len(x), 1500, replace=False)  # okunabilirlik için örnekleme
ax.scatter(x[idx], y[idx], alpha=0.25, s=15, color='#3498db', label='veri (örneklem)')
x_line = np.linspace(x.min(), x.max(), 100)
y_line = beta_manual[0] + beta_manual[1]*x_line
ax.plot(x_line, y_line, color='#e74c3c', lw=3,
        label=f'y = {beta_manual[0]:.2f} + {beta_manual[1]:.2f}·x\n(X^T X)^-1 X^T y ile bulundu')
ax.set_xlabel('Medyan Gelir (MedInc)')
ax.set_ylabel('Ev Fiyatı (100k $)')
ax.set_title('Normal Denklem: (XᵀX)⁻¹Xᵀy — Lineer Cebirle Regresyon')
ax.legend()
plt.tight_layout()
plt.show()

"""Gözlem: Elle lineer cebir ile bulduğumuz katsayılar, sklearn'ün optimizasyonla bulduğu katsayılarla birebir aynı çıkıyor. Bu, LinearRegression.fit() çağrısının arkasında aslında saf lineer cebir (matris tersi alma) olduğunu kanıtlıyor."""

# 7 - Matriste Rank Kavramı

#  Rank, bir dönüşümün çıktısının kapladığı uzayın boyut sayısıdır. "Full rank" bir matris bilgi kaybetmez; "rank-deficient" bir matris bir veya daha fazla boyutu ezer.

#  Eğer bir özellik diğerlerinin lineer kombinasyonuysa (örn. "toplam oda" = "yatak odası" + "diğer odalar"), veri matrisi eksik rank'lıdır ve bu durum regresyon katsayılarını kararsız hale getirir (çoklu doğrusal bağlantı problemi).

print("California Housing veri matrisinin rank'ı:", np.linalg.matrix_rank(X_house), "/ 8 özellik (FULL RANK)")

# Kasıtlı olarak doğrusal bağlantılı bir özellik ekleyelim: AveRooms + AveBedrms
AveRooms = X_house[:, house_feature_names.index('AveRooms')]
AveBedrms = X_house[:, house_feature_names.index('AveBedrms')]
redundant_feature = AveRooms + AveBedrms  # tamamen diğer ikisinin lineer kombinasyonu

X_redundant = np.column_stack([X_house, redundant_feature])
print("Yapay 'gereksiz' özellik eklenince rank:", np.linalg.matrix_rank(X_redundant), "/ 9 özellik (RANK EKSİK)")

# Kovaryans matrisinin ısı haritasıyla korelasyonu görelim
cov_before = np.corrcoef(X_house.T)
cov_after = np.corrcoef(X_redundant.T)

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
labels_before = house_feature_names
labels_after = house_feature_names + ['AveRooms+AveBedrms']

im0 = axes[0].imshow(cov_before, cmap='coolwarm', vmin=-1, vmax=1)
axes[0].set_xticks(range(len(labels_before))); axes[0].set_xticklabels(labels_before, rotation=90, fontsize=8)
axes[0].set_yticks(range(len(labels_before))); axes[0].set_yticklabels(labels_before, fontsize=8)
axes[0].set_title(f'Orijinal Korelasyon Matrisi\nRank = {np.linalg.matrix_rank(X_house)}')

im1 = axes[1].imshow(cov_after, cmap='coolwarm', vmin=-1, vmax=1)
axes[1].set_xticks(range(len(labels_after))); axes[1].set_xticklabels(labels_after, rotation=90, fontsize=8)
axes[1].set_yticks(range(len(labels_after))); axes[1].set_yticklabels(labels_after, fontsize=8)
axes[1].set_title(f'Gereksiz Özellik Eklenmiş Matris\nRank = {np.linalg.matrix_rank(X_redundant)} (eksik!)')

plt.colorbar(im0, ax=axes[0], fraction=0.046)
plt.colorbar(im1, ax=axes[1], fraction=0.046)
plt.tight_layout()
plt.show()

"""Gözlem: Yeni eklenen özellik (AveRooms+AveBedrms), diğer iki özellikle mükemmel korelasyona sahip (koyu kırmızı hücreler). Bu, X^T X matrisinin tersinemez hale gelmesine neden olur — Bölüm 6'daki Normal Denklem çözümü artık çalışmaz (np.linalg.inv hata verir veya sayısal olarak kararsızlaşır). Bu yüzden pratikte Ridge Regression gibi yöntemler kullanılır.

Matematiksel ve Pratik Sonucu: Bir önceki soruda kullandığımız Normal Denklemdeki $(\mathbf{X}^T \mathbf{X})^{-1}$ matris tersi alma işlemi, tam rank eksikliği durumunda patlar. Matrisin tersi alınamaz (singüler matris olur) veya sayısal olarak kararsız hale gelir (katsayılar aşırı büyür).Modellemede yeni nitelik türetirken var olan değişkenlerin basit doğrusal bileşimlerini eklemek model performansını artırmaz, aksine lineer cebirsel çözümleri bozar.
"""

# 8 - Özdeğerler ve Özvektörler

# Bir özvektör, bir dönüşüm sırasında yönünü değiştirmeyen, sadece özdeğeri kadar ölçeklenen özel bir vektördür: Av = λv.

# Veri biliminde PCA (Temel Bileşen Analizi), verinin kovaryans matrisinin özvektörlerini bulur.
# En büyük özdeğere sahip özvektör, verinin en çok yayıldığı yönü gösterir — yani "en bilgilendirici" yönü.

X4 = X_iris  # tüm 4 özellik
X4_centered = X4 - X4.mean(axis=0)

# Kovaryans matrisi
cov_matrix = np.cov(X4_centered.T)
print("Kovaryans matrisi (4x4):\n", cov_matrix)

# Özdeğer/özvektör ayrışımı
eigvals, eigvecs = np.linalg.eigh(cov_matrix)
# eigh küçükten büyüğe sıralar -> büyükten küçüğe çevirelim
order = np.argsort(eigvals)[::-1]
eigvals, eigvecs = eigvals[order], eigvecs[:, order]

print("\nÖzdeğerler (büyükten küçüğe):", eigvals)
print("\nAçıklanan varyans oranı:", eigvals / eigvals.sum())

fig, ax = plt.subplots(figsize=(7,5))
ax.bar(range(1,5), eigvals/eigvals.sum()*100, color='#3498db')
for i,v in enumerate(eigvals/eigvals.sum()*100):
    ax.text(i+1, v+1, f"{v:.1f}%", ha='center')
ax.set_xlabel('Özvektör (Temel Bileşen)')
ax.set_ylabel('Açıklanan Varyans (%)')
ax.set_title('Her Özdeğer, İlgili Özvektör Yönündeki\n"Bilgi Miktarını" Gösterir')
ax.set_xticks(range(1,5))
plt.tight_layout()
plt.show()

"""Gözlem: İlk özdeğer tek başına verinin varyansının büyük kısmını açıklıyor. Bu, 4 boyutlu Iris verisinin aslında "gerçekte" çok daha az boyutlu bir yapıda yaşadığı anlamına gelir"""

# 9 - Taban Değişimi: PCA ile Boyut İndirgeme

# Bir "taban" (basis), uzayı tanımlamak için seçtiğimiz eksen takımıdır.
# Standart î, ĵ tabanından, özvektörlerin oluşturduğu yeni bir tabana geçmek, veriyi farklı (genelde daha anlamlı) bir açıdan görmemizi sağlar.

# Veri bilimindeki karşılığı: PCA, veriyi orijinal özellik tabanından (sepal/petal ölçüleri), özvektör tabanına (temel bileşenler) taşır.
# İlk 2 temel bileşeni seçerek, 4 boyutlu veriyi bilgi kaybı minimum olacak şekilde 2 boyuta indirebiliriz.

# İlk 2 özvektör = yeni taban
W = eigvecs[:, :2]   # (4, 2) - taban değişim matrisi

# TABAN DEĞİŞİMİ: X_centered @ W  -> verinin yeni koordinatları
X_pca_manual = X4_centered @ W

# sklearn PCA ile doğrulama
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca_sklearn = pca.fit_transform(X4)

fig, axes = plt.subplots(1, 2, figsize=(14,6))
for cls in range(3):
    mask = y_iris == cls
    axes[0].scatter(X_pca_manual[mask,0], X_pca_manual[mask,1], color=colors[cls],
                     label=iris_target_names[cls], alpha=0.7)
    axes[1].scatter(X_pca_sklearn[mask,0], X_pca_sklearn[mask,1], color=colors[cls],
                     label=iris_target_names[cls], alpha=0.7)

axes[0].set_title("Elle Hesaplanan PCA\n(özvektör tabanına geçiş: X_centered @ W)")
axes[1].set_title("sklearn.decomposition.PCA\n(doğrulama)")
for ax in axes:
    ax.set_xlabel('1. Temel Bileşen'); ax.set_ylabel('2. Temel Bileşen')
    ax.legend(); ax.axhline(0,color='gray',lw=0.5); ax.axvline(0,color='gray',lw=0.5)
plt.tight_layout()
plt.show()

print("İki yöntem birbirine ne kadar yakın? Maks. mutlak fark:",
      np.abs(np.abs(X_pca_manual) - np.abs(X_pca_sklearn)).max())

"""Gözlem: 4 boyutlu Iris verisi, sadece 2 boyuta indirgenmesine rağmen 3 tür hâlâ net şekilde ayrılabiliyor — çünkü ilk 2 özvektör verinin varyansının çoğunu taşıyor. Elle yaptığımız hesap ile sklearn.PCA matematiksel olarak aynı sonucu veriyor -işaret farkları istisna."""

# 10 - SVD (Tekil Değer Ayrışımı)

# SVD, PCA'nın daha genel bir biçimidir ve gürültü azaltma, veri sıkıştırma, öneri sistemleri (matris tamamlama) gibi alanlarda kullanılır.
# California Housing verisini SVD ile sıkıştırıp, kaç bileşenle verinin çoğu bilgisinin korunduğunu görelim.

X_house_scaled = StandardScaler().fit_transform(X_house)
U, S_values, Vt = np.linalg.svd(X_house_scaled, full_matrices=False)

explained_var = (S_values**2) / np.sum(S_values**2)
cumulative_var = np.cumsum(explained_var)

fig, ax = plt.subplots(figsize=(8,5))
ax.bar(range(1, len(S_values)+1), explained_var*100, alpha=0.6, color='#3498db', label='Bileşen başına')
ax.plot(range(1, len(S_values)+1), cumulative_var*100, color='#e74c3c', marker='o', label='Kümülatif')
ax.axhline(95, color='gray', ls='--', lw=1, label='%95 eşiği')
ax.set_xlabel('Tekil Değer (Bileşen) Sayısı')
ax.set_ylabel('Açıklanan Varyans (%)')
ax.set_title('SVD: California Housing (8 özellik) İçin\nKaç Bileşen Yeterli?')
ax.legend()
plt.tight_layout()
plt.show()

n_95 = np.argmax(cumulative_var >= 0.95) + 1
print(f"Varyansın %95'ini korumak için yeterli bileşen sayısı: {n_95} / {X_house.shape[1]}")

"""Gözlem: 8 özelliğin tamamını taşımak yerine, çok daha az sayıda "tekil bileşenle" verinin büyük kısmı korunabiliyor. Bu, SVD'nin PCA ile aynı özü taşıdığını ama daha genel ve sayısal olarak daha kararlı bir formda olduğunu gösterir.

Boyut İndirgeme (Dimensionality Reduction): Temel Bileşenler Analizi'nin (PCA) arkasındaki matematiksel motor SVD'dir. Yüksek boyutlu verileri grafiksel olarak görselleştirmek veya modeli hızlandırmak için kullanılır.

Gürültü Temizleme (Denoising): Küçük tekil değerler genellikle verideki "gürültüyü" temsil eder. Bunlar elenerek verinin temiz hali elde edilir.

Doğal Dil İşleme (NLP): Metin madenciliğinde kelime-doküman matrislerinden anlamsal ilişkiler çıkarmak (Latent Semantic Analysis - LSA) için uygulanır.
"""
