# -*- coding: utf-8 -*-
"""veri-bilimi-pandas-groupby

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKt-YnZIgpW14YHk2ISoRphbIWW43rvy
"""

import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Alan optimizasyonu
dtypes = {
    "first_name" : "category", ## Bellek optimizasyonu icin category tipi, object(string) olarak saklanmaz.
    "gender" : "category",
    "type" : "category",
    "state" : "category",
    "party" : "category"
}

df = pd.read_csv("legislators-historical.csv",
                 dtype=dtypes,
                 usecols=list(dtypes) + ["birthday","last_name"],
                 parse_dates=["birthday"]
                )

## SELECT state, count(name) FROM df GROUP BY state ORDER BY state; sorgusuna yakinsar.

n_by_state = df.groupby("state")["last_name"].count()
n_by_state.head(10)

## SELECT state, gender, count(name) FROM df GROUP BY state, gender ORDER BY state, gender;

df.groupby(["state", "gender"])["last_name"].count()

## Pandas Groupby vs SQL

## SQL ile bir gruplama yaptığınızda (örneğin GROUP BY state, gender), sonuç tablosu düz (flat) bir tablo olarak döner.

## Sonuçta; state sütunu, gender sütunu ve hesapladığınız count sütunu olmak üzere yan yana 3 ayrı sütun görürsünüz.

## Bu klasik bir "tablo" görünümüdür.

## pandas ise state ve gender artık "sütun" değil, verinin "adresleri" (indeksleri) haline gelir. Sadece count sonucu bir "sütun" olarak görünür.

## DataFrameGroupBy lazy bir nesne, yani veriyi hemen parcalamaz yapacagin isleme gore hazirim mesaji verir bu da bellek optimizasyonu saglar.

df = pd.read_csv(
    "airqual.csv",
    parse_dates=[["Date", "Time"]],
    na_values = [-200],
    usecols=["Date", "Time", "CO(GT)", "T", "RH", "AH"]
    ).rename(
        columns={
        "CO(GT)": "co",
        "Date_Time": "tstamp",
        "T": "temp_c",
        "RH": "rel_hum",
        "AH": "abs_hum",
        }
    ).set_index("tstamp")

df.head(10)

df.index.min()
df.index.max()

day_names = df.index.day_name()
type(day_names)

day_names[:10]

df.groupby(day_names)["co"].mean()

hr = df.index.hour
df.groupby([day_names,hr])["co"].mean().rename_axis(["dow","hour"])

bins = pd.cut(df['temp_c'], bins=3, labels=('cool','warm','hot'))
df[['rel_hum', 'abs_hum']].groupby(bins).agg(['mean','median'])

type(bins)
bins.head()

df.groupby([df.index.year, df.index.quarter])['co'].agg(['max', 'min']).rename_axis(['year','quarter'])

df.resample('M')['co'].agg(['max', 'min'])

def parse_milisecond_timestamp(ts):
  return pd.to_datetime(ts, unit='ms')

df = pd.read_csv(
    'news.csv',
    sep='\t',
    header=None,
    index_col=0,
    names=["title", "url", "outlet", "category", "cluster", "host", "tstamp"],
    parse_dates=['tstamp'],
    date_parser=parse_milisecond_timestamp,
    dtype={
        "outlet": "category",
        "category": "category",
        "cluster": "category",
        "host": "category",
    },
)

df.groupby('outlet', sort=False)['title'].apply(
    lambda x: x.str.contains('Fed').sum()
).nlargest(10)

# Concat

df1 = pd.DataFrame(
        {
            "A": ["A0", "A1", "A2", "A3"],
            "B": ["B0", "B1", "B2", "B3"],
            "C": ["C0", "C1", "C2", "C3"],
            "D": ["D0", "D1", "D2", "D3"],
        },
        index=[0, 1, 2, 3],
    )


df2 = pd.DataFrame(
        {
            "A": ["A4", "A5", "A6", "A7"],
            "B": ["B4", "B5", "B6", "B7"],
            "C": ["C4", "C5", "C6", "C7"],
            "D": ["D4", "D5", "D6", "D7"],
        },
        index=[4, 5, 6, 7],
    )


df3 = pd.DataFrame(
        {
            "A": ["A8", "A9", "A10", "A11"],
            "B": ["B8", "B9", "B10", "B11"],
            "C": ["C8", "C9", "C10", "C11"],
            "D": ["D8", "D9", "D10", "D11"],
        },
        index=[8, 9, 10, 11],
    )


frames = [df1, df2, df3]

result = pd.concat(frames)

result