# -*- coding: utf-8 -*-
"""veri_bilimi_ornek_egzersiz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqZCOmxs53dGasuYY_xkNbR6mvP9BckU
"""

import pandas as pd
import numpy as np

# Musteri tablosu
musteriler = pd.DataFrame({
    'musteri_id': [1, 2, 3, 4, 5],
    'isim': ['Ayşe', 'Mehmet', 'Zeynep', 'Ali', 'Fatma'],
    'sehir': ['İstanbul', 'Ankara', 'İstanbul', 'İzmir', 'Ankara'],
    'yas': [28, 35, 22, 41, 30]
})

# Sipariş tablosu
siparisler = pd.DataFrame({
    'siparis_id': [101, 102, 103, 104, 105, 106, 107],
    'musteri_id': [1, 2, 1, 3, 2, 4, 1],
    'urun': ['Laptop', 'Telefon', 'Klavye', 'Monitör', 'Kulaklık', 'Tablet', 'Mouse'],
    'kategori': ['Bilgisayar', 'Telefon', 'Bilgisayar', 'Bilgisayar', 'Aksesuar', 'Telefon', 'Aksesuar'],
    'tutar': [15000, 8000, 450, 3200, 1200, 6500, 300],
    'tarih': pd.to_datetime(['2024-01-05','2024-01-08','2024-01-12',
                             '2024-01-15','2024-01-18','2024-01-20','2024-02-01'])
})

## Egzersiz 1: Her kategoride toplam kaç TL satış yapılmış? Sonuçları büyükten küçüğe sırala.

satis_tablosu = siparisler.groupby('kategori')['tutar'].sum().sort_values(ascending=False)

## Egzersiz 2: Her müşterinin toplam harcaması, sipariş sayısı ve ortalama sipariş tutarını tek bir DataFrame'de göster.
musteri_bilgileri = musteriler[['musteri_id', 'isim']]
musteri_ozet = siparisler.groupby('musteri_id')['tutar'].agg(['count', 'sum', 'mean'])
musteri_ozet.columns = ['siparis_sayisi', 'toplam_harcama', 'ortalama_tutar']
son_tablo = pd.merge(musteri_bilgileri, musteri_ozet, on='musteri_id', how='left')

son_tablo

## Egzersiz 3: Her kategorideki en pahalı ürünü bul.

indexler = siparisler.groupby('kategori')['tutar'].idxmax()
siparisler.loc[indexler]