# -*- coding: utf-8 -*-
"""veri-bilimi-pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bE0B4ORTKZsxlx2dIBJkYxEa3Bj682hr
"""

import pandas as pd
from google.colab import drive

## Yazma, Okuma ##

pd.DataFrame({
    "Yes": [50, 21],
    "No": [131,2]
})

pd.DataFrame({
    "Fatih" : ["Bunu begendim.", "Bu berbat."],
    "Busra" : ["Oldukca iyi.", "Fena degil."]
})

pd.DataFrame({
    "Fatih" : ["Bunu begendim.", "Bu berbat."],
    "Busra" : ["Oldukca iyi.", "Fena degil."]
},index=["KisiA","KisiB"])

pd.Series([1, 2, 3, 4, 5])

pd.Series([26, 19, 17], ['Galatasaray', 'Fenerbahce', 'Besiktas'], name='Sampiyonluklar')

df = pd.read_csv('ornek_veri.csv', index_col=1)
df.head()

## Indexleme, Secme, Atama ##

from faker import Faker
import random

fake = Faker('tr_TR')

#1000 satirlik dummy data

data = {
    'ID': range(1,1001),
    'Isim': [fake.name() for _ in range(1000)],
    'Yas': [random.randint(18, 65) for _ in range(1000)],
    'Sehir': [fake.city() for _ in range(1000)],
    'Maas': [random.randint(20000, 100000) for _ in range(1000)],
    'Katilim_Tarihi': [fake.date_between(start_date='-5y', end_date='today') for _ in range(1000)]
}

dummy_data = pd.DataFrame(data)
dummy_data.to_csv('buyuk_veri.csv', index=False)

dummy_data.Katilim_Tarihi[1]

## Integer-based secim -ILOC-

dummy_isimler = dummy_data.iloc[19:76:19,1]
print(dummy_isimler)

## Label-based secim -LOC-

dummy_data.loc[1:100,['Isim', 'Yas']]

## Sarta bagli secim

dummy_data.Yas > 25

dummy_data.loc[(dummy_data.Yas > 25) & (dummy_data.Maas < 50000), 'Sehir'] ## 25 yasindan buyuk ve maasi 50binden az olanlarin sehirleri ##

## Summary functions

dummy_data.describe()

yas_ort = dummy_data.Yas.describe().median()
yas_ort

## Group ve Sort islemleri

dummy_data.groupby('Maas').Maas.count()

dummy_data.groupby('Sehir').Maas.max()

## DataTypes

dummy_data.Maas.dtype

dummy_data.dtypes

## Renaming

dummy_data.rename(columns = { 'Yas' : 'Yasi' })

dummy_data.rename(index= {0: 'Arsoy Aksu'})