# -*- coding: utf-8 -*-
"""veri-bilimi-numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aagjv3J-AewPR6q5nmekPtZR-paQ70Bm
"""

import numpy as np

a = np.array([[1,2,3],[4,5,6], [7,8,9]])
a.shape

x = np.arange(9)

## Array ozellikleri

a.ndim ## boyutu verir (3)

a.shape ## kaca kaclik matris oldugunu verir (3x3).

len(a.shape) == a.ndim

a.size ## eleman sayisi (9)

## Array olusturma methodlari

np.zeros(2)

np.ones(3)

np.empty(2)

np.arange(5)

np.linspace(0,100,num=26) ## 0 ile 100 arasinda esit araliklarda 26 tane sayi uret.

## Add, Remove, Sort islemleri

arr = np.array([2,1,7,3,14,6])

np.sort(arr)

a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b)) ## birlestir

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis = 0)

## Bir arrayin sekli ve boyutu

array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example.ndim ## arrayin boyutunu verir

array_example.size ## arraydeki toplam eleman sayisini verir

array_example.shape ## arrayin boyutu, bir boyuttaki satir sayisi ve bir satirdaki eleman sayisi

## Reshape kullanimi

a = np.arange(9)

a.reshape((3,3))

## Array'e yeni boyut ekleme

a = np.arange(6)
a2 = a[np.newaxis, :]
a.shape

## Indexleme ve Slice islemi

data = np.array([[1, 2, 0, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
data[data < 6]

condition = (data > 5) & (data < 11)
data[condition]

##np.nonzero 0 olmayan elemanlarin indekslerini verir ve kondisyon alabilir.

np.nonzero(data < 6)

# Array islemleri

data = np.array([2,1])
ones = np.ones(2, dtype=np.int64)

data + ones

data * ones

data / ones

data - ones

a = np.arange(1,11)
a.sum()

## 2D arrayde eksen belirtilmeli

b = np.array([[1,2],[3,4]])
b.sum(axis = 1) ## axis degeri toplama isleminin hangi yonde yapilacagini belirtir. ornegin 0 sutun 1 yatay toplam vs.

## Broadcasting

data = np.array([1.0,3.0])
data * 1.6

## arrayi verilen bir sayi veya uygun olan baska bir array ile genisletir

## Random sayilar olusturma

rng = np.random.default_rng()

rng.random(10)

rng.standard_normal(10) ##Gauss dagilimi

rng.integers(low=0, high=10, size=5)

## unique veriler ve sayilari

a = np.array([1,1,1,2,3,4,5,5,6,7])
unique_values, unique_counts = np.unique(a, return_counts=1)

a_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.unique(a_2d, axis = 1)

## Multidimentional arrayleri duzlemek

a_2d = np.arange(8).reshape(2,4)
a_2d.flatten()

## flatten orijinal veriyi degistirmez, ravel degistirir.

